### ISSUE TITLE
Module not found issue 

### ISSUE THREAD

**Issue by Aitareis** [notunderctrl/image-generator-bot#2]
Throw error and cannot find config.json and index.js
I made sure to double check all codes so they are definitely in the right place, and when i use it in my computer it works, but when I try to activate it on a hosting service it wouldn't start because of this issue.

<img width="497" alt="image" src="https://github.com/notunderctrl/image-generator-bot/assets/134501476/494a6503-4396-402c-885d-3c5a0f234811">

**Comment by notunderctrl** [comment]
Did you cross check `config.json` exists a level above your src folder?
